-- Insert sample model configuration data for testing
-- This will add 3 test model configuration records to the model_configuration table

INSERT IGNORE INTO model_configuration (
    modelId, 
    modelType, 
    modelName, 
    containerId, 
    versionNumber, 
    apiUrl, 
    localModelFileDir, 
    remainingTrainingTimes, 
    billingUnit, 
    unitCost, 
    accumulatedUsage, 
    accumulatedCost, 
    configuration_type, 
    configuration_data, 
    version, 
    status, 
    creator, 
    updater, 
    createTime, 
    updateTime
) VALUES
(
    'MODEL001', 
    'GPT', 
    'GPT-3.5 Turbo', 
    'container_001', 
    'v1.0.0', 
    'https://api.openai.com/v1/chat/completions', 
    '/models/gpt35', 
    100, 
    'tokens', 
    0.002, 
    1500.00, 
    3.00, 
    'chat_completion', 
    '{"temperature": 0.7, "max_tokens": 1000}', 
    '1.0.0', 
    '启用', 
    '管理员', 
    '管理员', 
    NOW(), 
    NOW()
),
(
    'MODEL002', 
    'Claude', 
    'Claude-3 Sonnet', 
    'container_002', 
    'v2.1.0', 
    'https://api.anthropic.com/v1/messages', 
    '/models/claude3', 
    50, 
    'tokens', 
    0.003, 
    800.00, 
    2.40, 
    'text_generation', 
    '{"temperature": 0.5, "max_tokens": 2000}', 
    '2.1.0', 
    '启用', 
    '管理员', 
    '管理员', 
    NOW(), 
    NOW()
),
(
    'MODEL003', 
    'Gemini', 
    'Gemini Pro', 
    'container_003', 
    'v1.5.0', 
    'https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent', 
    '/models/gemini', 
    75, 
    'characters', 
    0.001, 
    2000.00, 
    2.00, 
    'content_generation', 
    '{"temperature": 0.8, "top_p": 0.9}', 
    '1.5.0', 
    '测试', 
    '管理员', 
    '管理员', 
    NOW(), 
    NOW()
);

-- Verify the data was inserted
SELECT COUNT(*) as total_models FROM model_configuration;
SELECT modelId, modelName, modelType, status, version FROM model_configuration ORDER BY createTime DESC;
